# for the usage see the Readme.md
graphhopper:
  datareader.file: /Users/michaelzilske/mini_nor_cal/mini_nor_cal-regional_transportation_network-osm_cutout-b6b883700478cea5de1bb2e895aec2c4cd97ef4f.osm.pbf
  gtfs.file: /Users/michaelzilske/mini_nor_cal/f-9qc-eldoradotransit~ca~us.zip,/Users/michaelzilske/mini_nor_cal/f-9qc7-unitransdavis.zip,/Users/michaelzilske/mini_nor_cal/f-9qcs-rosevilletransit.zip,/Users/michaelzilske/mini_nor_cal/f-9qc-placercountytransit.zip,/Users/michaelzilske/mini_nor_cal/f-9qc7-yolobusyolocounty.zip,/Users/michaelzilske/mini_nor_cal/f-amtrak~capitol~corridor.zip,/Users/michaelzilske/mini_nor_cal/f-9qc-yubasutter~ca~us.zip,/Users/michaelzilske/mini_nor_cal/f-9qce-sacramentoregionaltransit.zip


  graph.location: graph-mini_norcal
  graph.dataaccess.default_type: RAM_STORE

  gtfs.trip_based: true
  #gtfs.schedule_day: 2023-04-05,2023-05-10
  gtfs.schedule_day: 2022-09-22

  gtfs.max_transfer_interpolation_walk_time_seconds: 300

  #gtfs.free_walk: true

#  graph.flag_encoders: car

 # import.speedmodels_location: /speedmodels

  prepare.min_network_size: 800
  profiles:
    - name: foot
      vehicle: foot
      weighting: fastest
    - name: car
      vehicle: car
      weighting: fastest

  import.osm.ignored_highways: ''
  routing.max_visited_nodes: 4000000

server:
  # for some reason dropwizard expects this to be camel-cased...
  application_connectors:
    - type: http
      port: 8900
      max_request_header_size: 40KiB
      max_response_header_size: 40KiB
      accept_queue_size: 256
      # for security reasons bind to localhost
      bind_host: localhost
  admin_connectors:
    - type: http
      port: 9900
      bind_host: localhost

# see dropwizard documentation: https://www.dropwizard.io/1.3.5/docs/manual/configuration.html#logging
logging:
  level: INFO

  loggers:
    "com.graphhopper": INFO

  appenders:
    - type: console
      time_zone: UTC
      log_format: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    - type: file
      time_zone: UTC
      log_format: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
      current_log_filename: logs/matrix.log
      archive: false